# User Settings | Edit there as per required

title: SirKapil
url: "https://sirkapil.github.io/"
baseurl: "/accent"

# This will show up at the top of index page
site_heading: >
    Kapil <span class="faded">'s blog</span>

email: your@email.com
author: Kapil Chaudhary
description: >
    This is description.

# This will what will show against &copy; in the footer
copyright: Kapil Chaudhary
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    This is my bio.

permalink: /:title

# Comments are powered by disqus
comments: true
about_stub: >
       Hi this is srub

about_footer: true

twitter_username: kapil_rc
github_username: sirkapil
facebook_id: kapil05021996

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-69243698-7 # GA Tracking ID

# Social Stuff 
og_image: "images/accent.png"
twitter_image: "http://ankitsultana.com/images/accent.png?1234"

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
